config/routes.rb
Rails.application.routes.draw do
  #
  # #Page routes
  # root 'pages#index'
  # get 'about', to: 'pages#about'
  # get 'contact', to: 'pages#contact'
  # get 'terms', to: 'pages#terms'
  #
  # #Repair routes
  # get 'repairs', to: 'repairs#index', as: 'repair_index'
  # get 'repair/new', to: 'repairs#new', as: 'new_repair'
  # get 'repair/:id', to: 'repairs#show', as: 'repair'
  # post 'repair', to: 'repairs#create', as: 'repairs'
  # get 'repair/:id/edit', to: 'repairs#edit', as: 'edit_repair'
  # patch 'repair/:id', to: 'repairs#update'
  # put 'repair/:id', to: 'repairs#update'
  # patch 'repair/:id/pick_up', to: 'repairs#pick_up', as: 'pick_up_repair'
  # patch 'repair/:id/fix', to: 'repairs#fix', as: 'fix_repair'
  # patch 'repair/:id/deliver', to: 'repairs#deliver', as: 'deliver_repair'
  # patch 'repair/:id/cancel', to: 'repairs#cancel', as: 'cancel_repair'
  #
  #
  # #Device routes
  # get 'devices', to: 'devices#index', as: 'device_index'
  # get 'device/:id', to: 'devices#show', as: 'device'
  # get 'device/:id/edit', to: 'devices#edit', as: 'edit_device'
  # patch 'device/:id', to: 'devices#update'
  # put 'device/:id', to: 'devices#update'
  # get 'device/:id/fix', to: 'devices#fix', as: 'fix_device'
  #
  # #Address routes
  # get 'addresses', to: 'addresses#index', as: 'address_index'
  # get 'address/:id', to: 'addresses#show', as: 'address'
  # get 'address/:id/edit', to: 'addresses#edit', as: 'edit_address'
  # patch 'address/:id', to: 'addresses#update'
  # put 'address/:id', to: 'addresses#update'
  #
  # #User routes
  # get '/dashboard', to: 'users#dashboard', as: 'user_root'
  # devise_for :users

  #Admin routes
  get '/adash', to: 'admins#dashboard', as: 'admin_root'
  devise_for :admins

  #reps
  resources :reps, only: [:index, :show, :new, :create]

  #Maintenance Page
  root 'pages#maint'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rep.rb
class Rep < ApplicationRecord
  include Friendlyable

  validates_presence_of :name
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }
  validates_presence_of :age
  validates_presence_of :gender
  validates_presence_of :university

  enum gender: {
    male: 0,
    female: 1
  }
end

app/controllers/reps_controller.rb
class RepsController < ApplicationController
  layout 'maint'
  before_action :set_rep, only: [:show, :edit, :update]

  def index
  end

  def show
  end

  def new
    @rep = Rep.new
  end

  def create
    @rep = Rep.new(rep_params)

    if @rep.save
      RepMailer.confirm_application(@rep).deliver
      redirect_to @rep
    else
      render :new
    end
  end

  private
    def set_rep
      @rep = Rep.friendly.find(params[:id])
    end

    def rep_params
      params.require(:rep).permit(:name, :email, :age, :gender, :university)
    end
end

app/views/reps/index.html.haml
.fill
  = image_tag 'fix.png', alt: "Fixus logo", class: 'logo'
  %h2 Become a rep today
  %p
    = link_to "Click Here", new_rep_path
    = " to register now"

app/views/reps/new.html.haml
.fill
  = image_tag 'fix.png', alt: "Fixus logo", class: 'logo'
  .form
    %h2 Become a Rep
    = simple_form_for @rep do |f|
      = f.input :name, placeholder: "Full Name"
      = f.input :email, placeholder: "Email"
      = f.input :age, collection: 16..30
      = f.input :university, placeholder: "University"
      = f.input :gender, collection: Rep.genders.keys
      .form-actions
        = f.button :submit

app/views/reps/show.html.haml
.fill
  = image_tag 'fix.png', alt: "Fixus logo", class: 'logo'
  .rep
    %h3
      = "Rep ##{@rep.hash_id}"
    .info
      %p
        %span= "Name:   "
        = @rep.name
      %p
        %span= "Email:   "
        = @rep.email
      %p
        %span= "Age:   "
        = @rep.age
      %p
        %span= "University:   "
        = @rep.university
      %p
        %span= "Gender:   "
        = @rep.gender