config/routes.rb
Rails.application.routes.draw do
  #
  # #Page routes
  # root 'pages#index'
  # get 'about', to: 'pages#about'
  # get 'contact', to: 'pages#contact'
  # get 'terms', to: 'pages#terms'
  #
  # #Repair routes
  # get 'repairs', to: 'repairs#index', as: 'repair_index'
  # get 'repair/new', to: 'repairs#new', as: 'new_repair'
  # get 'repair/:id', to: 'repairs#show', as: 'repair'
  # post 'repair', to: 'repairs#create', as: 'repairs'
  # get 'repair/:id/edit', to: 'repairs#edit', as: 'edit_repair'
  # patch 'repair/:id', to: 'repairs#update'
  # put 'repair/:id', to: 'repairs#update'
  # patch 'repair/:id/pick_up', to: 'repairs#pick_up', as: 'pick_up_repair'
  # patch 'repair/:id/fix', to: 'repairs#fix', as: 'fix_repair'
  # patch 'repair/:id/deliver', to: 'repairs#deliver', as: 'deliver_repair'
  # patch 'repair/:id/cancel', to: 'repairs#cancel', as: 'cancel_repair'
  #
  #
  # #Device routes
  # get 'devices', to: 'devices#index', as: 'device_index'
  # get 'device/:id', to: 'devices#show', as: 'device'
  # get 'device/:id/edit', to: 'devices#edit', as: 'edit_device'
  # patch 'device/:id', to: 'devices#update'
  # put 'device/:id', to: 'devices#update'
  # get 'device/:id/fix', to: 'devices#fix', as: 'fix_device'
  #
  # #Address routes
  # get 'addresses', to: 'addresses#index', as: 'address_index'
  # get 'address/:id', to: 'addresses#show', as: 'address'
  # get 'address/:id/edit', to: 'addresses#edit', as: 'edit_address'
  # patch 'address/:id', to: 'addresses#update'
  # put 'address/:id', to: 'addresses#update'
  #
  # #User routes
  # get '/dashboard', to: 'users#dashboard', as: 'user_root'
  # devise_for :users

  #Admin routes
  get '/adash', to: 'admins#dashboard', as: 'admin_root'
  devise_for :admins

  #reps
  resources :reps, only: [:index, :show, :new, :create]

  #Maintenance Page
  root 'pages#maint'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/about.html.haml
%h1 Pages#about
%p Find me in app/views/pages/about.html.haml

app/views/pages/contact.html.haml
%h1 Pages#contact
%p Find me in app/views/pages/contact.html.haml

app/views/pages/index.html.haml
.poster.indexposter
  .coloroverlay
  .head
    = link_to "Log in", new_user_session_path
  .else
    .image
      = image_tag 'fix.png', alt: "Fixus logo", class: 'logo_icon'
    .text
      .cont
        %h1 Welcome to Fixus
        %p No matter what you've got that needs fixing; phones, laptops, tablets, and more; we can help you fix it. At competitive rates and in record time, you won't ever regret doing busiiness with us.
        .links
          = link_to 'Sign up/Fix your device', new_repair_path, class: "btn light"
          = link_to 'Link for Business', new_repair_path, class: "btn"
          = link_to 'Learn more about us', about_path, class: "btn"






-# .banner
-#   .big= image_tag 'fixus_icon.svg', alt: "Fixus logo", class: 'fixus'
-#   .cont
-#     %h1
-#       Need a quick fix?
-#       %br
-#       We can help!
-#     %p Get it fixed by experts in record time without ever leaving your house!
-#     = link_to 'Fix It Now', new_repair_path, class: 'button highlight'
-#
-# .section
-#   .left
-#     .span.image
-#       = image_tag 'busi.png', alt: "For businesses", class: 'fixus'
-#     .cont
-#       %h2 For Businesses
-#       %p Give your employees the time to focus on more pressing tasks, like meetings and other business chores. We offer you reasonable prices while assuring you of our best professional service at all times.
-#   .divide
-#   .right
-#     .span.image
-#       = image_tag 'indi.png', alt: "For individuals", class: 'fixus'
-#     .cont
-#       %h2 For Individuals
-#       %p We take care of your needs, from repairs of phones, tablets, laptops, to purchase of accessories, to reselling of devices, Fixus is here for you. Join us today, you won't regret it.
-#
-# .testimonials
-#   %h3 Here's what people have to say about FIXUS
-#   .tflex
-#     .testimonial
-#       = image_tag 'ms_maribell.png', alt: "ms_maribell", class: 'fixus'
-#       %p Thank you Fixus for fixing my tab's memory asap
-#       %span @Ms_maribell via Instagram
-#     .testimonial
-#       = image_tag 'tejirii.png', alt: "tejirii", class: 'fixus'
-#       %p Thanks for fixing my laptop and for the lovely laptop pouch
-#       %span @tejirii via Instagram
-#     .testimonial
-#       = image_tag 'pahpee_jay.png', alt: "pahpee_jay", class: 'fixus'
-#       %p Thanks for getting me my files back and fixing my hard drive, the service was excellent.
-#       %span @pahpee_jay via Instagram

app/views/pages/maint.html.haml
.fill
  = image_tag 'fix.png', alt: "Fixus logo", class: 'fixus_icon'
  = image_tag 'fixus_logo_c.svg', alt: "Fixus logo", class: 'fixus_logo'
  %p
    This site is currently under maintenance. We'll be back soon. For now you can reach us on
    = link_to 'Instagram ( @_fixus ).', 'https://www.instagram.com/_fixus/'
    If you want to become a rep in your university, please
    = link_to 'click here', reps_path

app/views/pages/terms.html.haml
.tsection
  %h2 Terms of Service

  %h3 Online Privacy Policy
  %p Fixus Online Privacy Policy Fixus and its wholly-owned subsidiaries believe that privacy is important to the success and use of the Internet. This statement sets forth Fixus policy and describes the practices that we will follow with respect to the privacy of the information of users of this site. Should you have any questions about this policy or our practices, please send an email to Fixusbot@gmail.com
  %p You can also call us at 0705 6667 362, 0705 658 1641 or 07051898359
  %h3 What Personal Information We Collect
  %p Fixus collects your personal information online when you voluntarily provide it to us. If you choose to register online, we ask you to provide limited personal information, such as your name, address, telephone number and/or email address. We also collect information that will allow you to establish a username and password if you would like to do that.
  %h3 How to Review and Change Your Personal Information
  %p If you register for a Fixus account, you may review and change your personal information by logging in to Fixus  and clicking "Manage my Account”.
  %h3 How We Use Personal Information That We Collect Online
  %h4 Internal Uses
  %p We may use your personal information within Fixus: (1) to provide you with the services and products you request or that have been ordered and/or requested by you; (2) to answer questions about our services; billing, payment methods or use of our website; (3) to process or collect payments for our services, (4) to conduct customer surveys; and (5) to contact you about the products and services that we offer.
  %h3 Disclosure of Personal Information to Third Parties
  %p We will not disclose any personal information to any third party (excluding our contractors to whom we may provide such information for the limited purpose of providing services to us and who are obligated to keep the information confidential), unless (1) you have authorized us to do so; (2) we are legally required to do so, for example, in response to a subpoena, court order or other legal process and/or, (3) it is necessary to protect our property rights related to this website. We also may share aggregate, non-personal information about website usage with unaffiliated third parties. This aggregate information does not contain any personal information about our users.

  %h3 Cookie Placement

  %p The Fixus site, like many other commercial sites, may use a standard technology called "cookies" to collect information about how our site is used. Cookies were designed to help a website operator determine that a particular user had visited the site previously and thus save and remember any preferences that may have been set. We may use cookies to keep track of information about your current web browsing session which will be discarded as soon as you log out or close your web browser. This information also allows us to statistically monitor how many people are using our site and for what purpose. We may also make use of “persistent or memory based” cookies, which remain on your computer’s hard drive until you delete them. Examples include our use of these cookies to pre-populate forms you complete on our website based on information you have previously provided to us, enable interest-based advertising and collect information about your web browsing history. Although you have the ability to modify your browser to either accept all cookies, notify you when a cookie is sent, or reject all cookies, it may not be possible to utilize our services if you reject cookies.
  %p Fixus uses the services of Google Analytics, and may use other similar services, to collect and analyze statistical data about visitors to our website. We also use Google advertising services, including a remarketing function, and may use other similar services, to arrange for you to see Fixus advertisements when you visit certain third party websites. These analytic and advertising services do not collect personally identifiable information. You may elect to opt out of the use of non-personally identifiable data by Google Analytics by downloading and installing an add-on to your web browser found here. You may find out more about how Google Analytics collects and processes data by visiting “How Google uses data when you use our partners’ sites or apps,” found here. You may also opt out of the Google AdWords service we use to serve ads, and which service also collects non-personally identifiable information, by visiting the Google Ad Settings page here.

  %h3 How We Protect Information Online

  %p We exercise great care to protect your personal information. This includes, among other things, using industry standard techniques such as firewalls, encryption, and intrusion detection. As a result, while we strive to protect your personal information, we cannot ensure or warrant the security of any information you transmit to us or receive from us. This is especially true for information you transmit to us via email since we have no way of protecting that information until it reaches us since email does not have the security features that are built into our websites.

  %p In addition, we limit Fixus' employees and contractors' access to personal information. Only those employees and contractors with a business reason to know have access to this information. We educate our employees about the importance of maintaining confidentiality of customer information.
  %p We review our security arrangements from time to time as we deem appropriate.

  %h3 How can you help protect your information?

  %p If you are using the Fixus website for which you registered and choose a password, we recommend that you do not divulge your password to anyone. We will never ask you for your password in an unsolicited phone call or in an unsolicited email. Also remember to sign out of the Fixus website and close your browser window when you have finished your work. This is to ensure that others cannot access your personal information and correspondence if others have access to your computer.

  %h3 Links to Other Sites

  %p We want to provide site visitors valuable information, services and products. Featured programs and other site content within the Fixus site may link our users to third party sites. Fixus does not control and is not responsible for practices of any third-party websites.

  %h4 Note

  %p From time to time, we may change this privacy statement. For example, as we update and improve our services, new features may require modifications to the privacy statement. Accordingly, please check back periodically.

  %h3 Non-Discrimination Notice

  %p Fixus and its subsidiaries (Fixus) complies with applicable Federal civil rights laws and does not discriminate on the basis of race, color, national origin, age, disability, or sex. Quest Diagnostics does not exclude people or treat them differently because of race, color, national origin, age, disability, or sex.

  %h3 Intellectual property rights provision:

  %p The Site and its original content, features, and functionality are owned by [Owner of Website] and are protected by international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws

  %h3 Payment Policy

  %p The acceptable methods of payment for Fixus' services are as follows: Cash payments and bank transfers. At Fixus' our number one priority is customer convenience so we admonish you to please use whichever method is most convenient for you. You will be charged a standard pickup fee at the beginning of every transaction. Also we require a payment of 70% in advance before we commence any repairs on your devices, this is to ensure your full commitment to the service and the balance of 30% is to be paid in full on delivery of your device.

  %h3 Shipping policy

  %p All pickups and deliveries are outsourced to a third party courier service and as such, our liability only begins when your goods have been delivered to us and are in our possession. We will not be liable for damages or loss of items in the course of transit. Also in the case of late delivery of your product back to you, please bear with us as human error is a real thing even though we try to keep it to a minimum at Fixus.

  %h3 Termination Clause

  %p We may terminate your access to the Site, without cause or notice, which may result in the forfeiture and destruction of all information associated with your account. All provisions of this Agreement that, by their nature, should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity, and limitations of liability.