config/routes.rb
Rails.application.routes.draw do
  #
  # #Page routes
  # root 'pages#index'
  # get 'about', to: 'pages#about'
  # get 'contact', to: 'pages#contact'
  # get 'terms', to: 'pages#terms'
  #
  # #Repair routes
  # get 'repairs', to: 'repairs#index', as: 'repair_index'
  # get 'repair/new', to: 'repairs#new', as: 'new_repair'
  # get 'repair/:id', to: 'repairs#show', as: 'repair'
  # post 'repair', to: 'repairs#create', as: 'repairs'
  # get 'repair/:id/edit', to: 'repairs#edit', as: 'edit_repair'
  # patch 'repair/:id', to: 'repairs#update'
  # put 'repair/:id', to: 'repairs#update'
  # patch 'repair/:id/pick_up', to: 'repairs#pick_up', as: 'pick_up_repair'
  # patch 'repair/:id/fix', to: 'repairs#fix', as: 'fix_repair'
  # patch 'repair/:id/deliver', to: 'repairs#deliver', as: 'deliver_repair'
  # patch 'repair/:id/cancel', to: 'repairs#cancel', as: 'cancel_repair'
  #
  #
  # #Device routes
  # get 'devices', to: 'devices#index', as: 'device_index'
  # get 'device/:id', to: 'devices#show', as: 'device'
  # get 'device/:id/edit', to: 'devices#edit', as: 'edit_device'
  # patch 'device/:id', to: 'devices#update'
  # put 'device/:id', to: 'devices#update'
  # get 'device/:id/fix', to: 'devices#fix', as: 'fix_device'
  #
  # #Address routes
  # get 'addresses', to: 'addresses#index', as: 'address_index'
  # get 'address/:id', to: 'addresses#show', as: 'address'
  # get 'address/:id/edit', to: 'addresses#edit', as: 'edit_address'
  # patch 'address/:id', to: 'addresses#update'
  # put 'address/:id', to: 'addresses#update'
  #
  # #User routes
  # get '/dashboard', to: 'users#dashboard', as: 'user_root'
  # devise_for :users

  #Admin routes
  get '/adash', to: 'admins#dashboard', as: 'admin_root'
  devise_for :admins

  #reps
  resources :reps, only: [:index, :show, :new, :create]

  #Maintenance Page
  root 'pages#maint'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.haml
#footer
  .links
    %span#title Features
    = link_to 'Repair a Device', new_repair_path
    = link_to 'Dashboard', user_root_path
    = link_to "Repairs", repair_index_path
    = link_to "Devices", device_index_path
    = link_to "Addresses", address_index_path

  .links
    %span#title Resources
    = link_to "Terms of Service", terms_path
    = link_to "Contact Us", '#'
    = link_to "Help", '#'

  .links
    %span#title Company
    = link_to "About Fixus", '#'
    = link_to "About Crystal Haze", '#'


  #logos
    = image_tag 'fixus_icon.svg', alt: "Fixus logo", class: 'fixus'
    = image_tag 'fixus_icon.svg', alt: "Crystal Haze logo", class: 'crystal_haze'

  #copyright © 2017 Crystal Haze

app/views/layouts/_header.html.haml
#header.cf
  %a{:href => root_path, :class => 'logo'}
    - if mobile_device?
      = image_tag "fixus_icon_white.svg", alt: "Fixus logo"
    - else
      = image_tag "fixus_logo_white.svg", alt: "Fixus logo"

  %li#title Menu
  #nav
    - if person_signed_in?
      = link_to "Repairs", repair_index_path
      = link_to "Devices", device_index_path
      = link_to "Addresses", address_index_path
    - if user_signed_in?
      = link_to "Sign Out", destroy_user_session_path, method: :delete
    - elsif admin_signed_in?
      = link_to "Sign Out", destroy_admin_session_path, method: :delete
    - else
      = link_to 'Repair a Device', new_repair_path
      = link_to "Log in", new_user_session_path
      = link_to "Sign up", new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Fixus
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    - if mobile_device?
      = stylesheet_link_tag 'mobile', media: 'all', 'data-turbolinks-track': 'reload'
    - else
      = stylesheet_link_tag 'desktop', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = render 'layouts/header' unless @nhnf

    - if notice
      #flash
        %p= notice
    - if alert
      #flash.alert
        %p= alert

    = yield

    = render 'layouts/footer' unless @nhnf

app/views/layouts/maint.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Fixus
    = csrf_meta_tags
    - if mobile_device?
      = stylesheet_link_tag 'maint_mobile', media: 'all', 'data-turbolinks-track': 'reload'
    - else
      = stylesheet_link_tag 'maint', media: 'all', 'data-turbolinks-track': 'reload'

  %body
    = yield